# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-framework-example',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/nbdev-framework-example',
                'lib_path': 'nbdev_framework_example'},
  'syms': {}}
